import * as _ from "lodash";
import { AST, Fmt } from "../type";
import { sortParams } from "../template";
import { seg } from "../fmt";
import * as F from "../fmt";

const simpleCodeName = {
    "AAVE": "AAVE",
    "Anglicised": "Anglicised",
    "Anglicized": "Anglicised",
    "ar-Cairene": "Cairene",
    "Cairene": "Cairene",
    "Arvanite": "Arvanite",
    "Ashkenazi Hebrew": "Ashkenazi Hebrew",
    "Ashkenazi": "Ashkenazi Hebrew",
    "Australia": "Australia",
    "AU": "Australia",
    "Aus": "Australia",
    "AusE": "Australia",
    "BE-nl": "Belgium",
    "BE": "Belgium",
    "Beijing": "Beijing",
    "Boston": "Boston",
    "Bos": "Boston",
    "Brazil": "Brazil",
    "BP": "Brazil",
    "BR": "Brazil",
    "Brazilian Portuguese": "Brazil",
    "Canada": "Canada",
    "CA": "Canada",
    "Canadian": "Canada",
    "Canadian Shift": "Canadian Vowel Shift",
    "Canadian shift": "Canadian Vowel Shift",
    "Canadian Vowel Shift": "Canadian Vowel Shift",
    "Canadian vowel shift": "Canadian Vowel Shift",
    "Carioca": "Carioca",
    "RJ": "Carioca",
    "Castilian": "Castilian",
    "Spain": "Castilian",
    "Central Catalan": "Central",
    "central Germany": "central Germany",
    "central German": "central Germany",
    "Central German": "central Germany",
    "Central Germany": "central Germany",
    "Central Scotland": "Central Scotland",
    "Classical": "Classical",
    "Classical Sanskrit": "Classical",
    "Connacht": "Connacht",
    "cy-N": "North Wales",
    "cy-g": "North Wales",
    "cy-S": "South Wales",
    "cy-h": "South Wales",
    "Dari": "Dari",
    "Delhi": "Delhi Hindi",
    "Ecclesiastical": "Ecclesiastical",
    "Egyptological": "Egyptological",
    "FS": "FS",
    "FV": "French Flanders",
    "Gheg": "Gheg",
    "Givi": "Givi",
    "hbo": "Biblical Hebrew",
    "Biblical Hebrew": "Biblical Hebrew",
    "horse-hoarse": "without the horse–hoarse merger",
    "hy-E": "Eastern Armenian",
    "hy-IR": "Eastern Armenian - Iran",
    "hy-W": "Western Armenian",
    "hy-Y": "Eastern Armenian - Yerevan",
    "IL": "Modern Israeli Hebrew",
    "Israeli Hebrew": "Modern Israeli Hebrew",
    "Modern Hebrew": "Modern Israeli Hebrew",
    "Modern Israeli": "Modern Israeli Hebrew",
    "Modern Israeli Hebrew": "Modern Israeli Hebrew",
    "Modern/Israeli Hebrew": "Modern Israeli Hebrew",
    "InE": "Indian English",
    "IR": "Iranian Persian",
    "Ireland": "Ireland",
    "HE": "Ireland",
    "IE": "Ireland",
    "Italian Hebrew": "Italian Hebrew",
    "Johor-Selangor": "Johor-Selangor",
    "Kabul, Peshawar": "Kabul, Peshawar",
    "Kandahar": "Kandahar",
    "ps-Kandahar": "Kandahar",
    "Latinate": "Latinate",
    "Midwestern US": "Midwestern US",
    "Midwest US": "Midwestern US",
    "Midwest US English": "Midwestern US",
    "Midwestern US English": "Midwestern US",
    "Mizrahi Hebrew": "Mizrahi Hebrew",
    "Mizrahi": "Mizrahi Hebrew",
    "Mizrakhi": "Mizrahi Hebrew",
    "Mizrachi": "Mizrahi Hebrew",
    "Mizrakhi Hebrew": "Mizrahi Hebrew",
    "Mizrachi Hebrew": "Mizrahi Hebrew",
    "Munster": "Munster",
    "Netherlands": "Netherlands",
    "NL": "Netherlands",
    "New York": "NYC",
    "NY": "NYC",
    "NYC": "NYC",
    "New Zealand": "New Zealand",
    "NZ": "New Zealand",
    "non-rhotic": "non-rhotic",
    "nonrhotic": "non-rhotic",
    "northern and central Germany": "northern Germany, central Germany",
    "north and central German": "northern Germany, central Germany",
    "North and Central German": "northern Germany, central Germany",
    "north and central Germany": "northern Germany, central Germany",
    "North and Central Germany": "northern Germany, central Germany",
    "northern and central German": "northern Germany, central Germany",
    "Northern and Central German": "northern Germany, central Germany",
    "Northern and Central Germany": "northern Germany, central Germany",
    "Northern England": "Northern England",
    "North England": "Northern England",
    "northern Germany": "northern Germany",
    "north German": "northern Germany",
    "North German": "northern Germany",
    "north Germany": "northern Germany",
    "North Germany": "northern Germany",
    "northern German": "northern Germany",
    "Northern German": "northern Germany",
    "Northern Germany": "northern Germany",
    "Northern Scotland": "Northern Scotland",
    "Palestinian Hebrew": "Palestinian Hebrew",
    "Philippine": "Philippine",
    "Philippines": "Philippine",
    "Portugal": "Portugal",
    "EP": "Portugal",
    "PT": "Portugal",
    "ps-Kabul": "Kabuli",
    "Quetta": "Quetta",
    "rhotic": "rhotic",
    "Riau-Lingga": "Riau-Lingga",
    "São Paulo": "São Paulo",
    "Scotland": "Scotland",
    "Sephardi Hebrew": "Sephardi Hebrew",
    "Sephardi": "Sephardi Hebrew",
    "Sistani": "Sistani",
    "South Africa": "South Africa",
    "SAE": "South Africa",
    "South Brazil": "South Brazil",
    "southern Germany": "southern Germany",
    "south German": "southern Germany",
    "South German": "southern Germany",
    "south Germany": "southern Germany",
    "South Germany": "southern Germany",
    "southern German": "southern Germany",
    "Southern German": "southern Germany",
    "Southern Germany": "southern Germany",
    "Southern Scotland": "Southern Scotland",
    "St. Louis": "St. Louis (Missouri)",
    "STL": "St. Louis (Missouri)",
    "standard": "standard",
    "Standard": "standard",
    "Swedish": "Swedish",
    "Syrian Hebrew": "Syrian Hebrew",
    "Tajik": "Tajik",
    "Tajiki": "Tajik",
    "Tehrani": "Tehrani",
    "Tiberian Hebrew": "Tiberian Hebrew",
    "Tiberian": "Tiberian Hebrew",
    "Tosk": "Tosk",
    "UK": "UK",
    "British": "UK",
    "Ulster": "Ulster",
    "US": "US",
    "Vedic Sanskrit": "Vedic",
    "Vedic": "Vedic",
    "Rigvedic": "Vedic",
    "Vulgar": "Vulgar",
    "Wales": "Wales",
    "Welsh": "Wales",
    "Wardak": "Wardak",
    "Wazirwola": "Wazirwola",
    "Yemenite Hebrew": "Yemenite Hebrew"
};


// https://en.wiktionary.org/wiki/Template:accent
// {{a|US|Canada}}
function a(word: string, raw: AST.Parameter[]): Fmt {
    const {named, unnamed} = sortParams(raw, word);

    const complexCodeName = {
        "cot-caught": [F.seg("cot", true), F.seg("–"), F.seg("caught", true), F.seg(" merger")],
        "caught-cot": [F.seg("cot", true), F.seg("–"), F.seg("caught", true), F.seg(" merger")],
        "distinción": [F.seg("z", true), F.seg("–"), F.seg("s", true), F.seg(" distinction")],
        "father-bother": [F.seg("father", true), F.seg("–"), F.seg("bother", true), F.seg(" merger")],
        "lleísmo": [F.seg("ll", true), F.seg("–"), F.seg("y", true), F.seg(" distinction")],
        "Mary-marry-merry": [F.seg("Mary", true), F.seg("–"), F.seg("marry", true), F.seg("–"), F.seg("merry", true), F.seg(" merger")],
        "Mmmm": [F.seg("Mary", true), F.seg("–"), F.seg("marry", true), F.seg("–"), F.seg("merry", true), F.seg(" merger")],
        "non-Mary-marry-merry": [F.seg("Mary", true), F.seg("–"), F.seg("marry", true), F.seg("–"), F.seg("merry", true), F.seg(" distinction")],
        "nMmmm": [F.seg("Mary", true), F.seg("–"), F.seg("marry", true), F.seg("–"), F.seg("merry", true), F.seg(" distinction")],
        "pin-pen": [F.seg("pin", true), F.seg("–"), F.seg("pen", true), F.seg(" merger")],
        "pen-pin": [F.seg("pin", true), F.seg("–"), F.seg("pen", true), F.seg(" merger")],
        "seseo": [F.seg("seseo", true), F.seg(" merger")],
        "yeísmo": [F.seg("ll", true), F.seg("–"), F.seg("y", true), F.seg(" neutralization")]
    };
    let result = [F.seg(`(`)];

    // places
    unnamed.forEach((place, i) => {
        const key = F.extractText(place);
        const simpleValue = simpleCodeName[key];
        const complexValue = complexCodeName[key];
        if (i !== 0)
            result = F.add(result, `, `);

        if (simpleValue)
            result = F.add(result, `${simpleValue}`);
        else if (complexValue)
            result = F.concat(result, complexValue);
        else
            result = F.add(result, `${key}`);
    });
    result = F.add(result, `)`);
    return result
}


export default a;
